services:
  backend:
    build: ./ellty-backend
    ports:
      - '3000:3000'
    env_file:
      - ./ellty-backend/.env
    depends_on:
      - db

  frontend:
    build: ./ellty-frontend
    ports:
      - '5173:5173'
    env_file:
      - ./ellty-frontend/.env
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: elltydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
